import { NextRequest } from 'next/server';
import { db } from '@/lib/db';
import { ok, fail, guardError, readJson } from '@/lib/api';
import { requireStaff } from '@/lib/guard';
import { appendAuditLog } from '@/lib/audit';
import { assembleDeclarationForShipment, UnknownRegionError } from '@/lib/asycuda-service';
import { generateSadXml, xmlWellFormed, STATUS_LABELS, type FilingStatus } from '@/lib/engine/asycuda';
import crypto from 'node:crypto';

interface GenerateBody {
  shipmentId?: string;
  country?: string;
  office?: string;
  officeOfEntry?: string;
  declarationType?: string;
  currencyCode?: string;
  exchangeRate?: number;
  locationOfGoods?: string;
  deferredPaymentAccount?: string;
}

/**
 * POST /api/asycuda/generate — re-validates server-side (a declaration with
 * ANY error is refused), generates the SAD XML, stores it encrypted in the
 * vault store, records the filing with its timeline and mirrors it as a
 * declaration document in the vault. XML generation is staff-only.
 */
export async function POST(req: NextRequest) {
  try {
    const s = await requireStaff(req);
    const body = await readJson<GenerateBody>(req);
    if (!body.shipmentId || !body.country) return fail(400, 'MISSING_FIELDS', 'shipmentId and country are required.');

    let assembled;
    try {
      assembled = await assembleDeclarationForShipment(s.tenantId, body.shipmentId, { ...body, country: body.country! });
    } catch (err) {
      if (err instanceof UnknownRegionError) return fail(400, 'BAD_REGION', err.message);
      if ((err as { code?: string }).code === 'NOT_FOUND') return fail(404, 'NOT_FOUND', 'Shipment not found.');
      throw err;
    }
    if (assembled.errors.length) {
      return fail(422, 'VALIDATION_FAILED', 'The declaration has blocking errors — fix them before generating the XML.', {
        errors: JSON.stringify(assembled.errors),
      });
    }

    const xml = generateSadXml(assembled.declaration);
    const wf = xmlWellFormed(xml);
    if (!wf.ok) return fail(500, 'XML_INVALID', `Generated XML failed well-formedness check: ${wf.error}`);

    const { mkdir, writeFile } = await import('fs/promises');
    const path = await import('path');
    const { vaultEncrypt } = await import('@/lib/vault-crypto');
    const xmlBuf = Buffer.from(xml, 'utf8');
    const checksum = crypto.createHash('sha256').update(xmlBuf).digest('hex');
    const fileName = `SAD-${assembled.declaration.country}-${assembled.context.shipmentReference.replace(/[^\w.-]+/g, '_')}.xml`;
    const storageKey = `asycuda/${crypto.randomUUID()}-${fileName}`;
    const abs = path.join(process.cwd(), 'upload', storageKey);
    await mkdir(path.dirname(abs), { recursive: true });
    await writeFile(abs, vaultEncrypt(xmlBuf));

    const now = new Date().toISOString();
    const timeline = [{ status: 'xml_generated', at: now, byName: assembled.context.tenantName, note: `SAD XML generated (${checksum.slice(0, 12)}…); ${assembled.errors.length} errors, ${assembled.warnings.length} warnings at validation.` }];

    const [filing] = await db.$transaction([
      db.customsFiling.create({
        data: {
          tenantId: s.tenantId,
          shipmentId: body.shipmentId,
          country: assembled.declaration.country,
          declarationType: assembled.declaration.general.boxDeclarationType,
          office: assembled.declaration.general.boxOffice,
          cpc: assembled.declaration.items[0]?.box37Cpc || '',
          currencyCode: assembled.declaration.general.boxCurrencyCode,
          exchangeRate: assembled.declaration.general.boxExchangeRate,
          status: 'xml_generated',
          declarationJson: JSON.stringify(assembled.declaration),
          validationJson: JSON.stringify({ errors: assembled.errors, warnings: assembled.warnings }),
          xmlStorageKey: storageKey,
          xmlChecksum: checksum,
          timelineJson: JSON.stringify(timeline),
          createdById: s.userId,
        },
      }),
      db.document.create({
        data: {
          tenantId: s.tenantId,
          shipmentId: body.shipmentId,
          groupKey: crypto.randomUUID(),
          version: 1,
          isCurrent: true,
          type: 'declaration',
          title: `ASYCUDA SAD ${assembled.declaration.country} — ${assembled.context.shipmentReference}`,
          fileName,
          mimeType: 'application/xml',
          fileSize: xmlBuf.length,
          storageKey,
          checksum,
          notes: 'Generated by CaribClear e-Filing from real shipment + landed-cost data. Validate against the national XSD on first transmission; lodgement is done by the registered declarant on the administration portal.',
          uploadedById: s.userId,
        },
      }),
    ]);

    await appendAuditLog({
      tenantId: s.tenantId, userId: s.userId, action: 'asycuda.xml_generated',
      entityType: 'customs_filing', entityId: filing.id,
      metadata: { country: filing.country, shipment: assembled.context.shipmentReference, checksum, office: filing.office },
    });

    return ok({
      filing: { ...filing, statusLabel: STATUS_LABELS[filing.status as FilingStatus] },
      warnings: assembled.warnings,
      context: assembled.context,
    }, 201);
  } catch (err) { return guardError(err); }
}
